'use strict';
const english = {
  heroPromise: 'A research agent that thinks and acts.',
  heroEyebrow: 'LEMVO / THINKING RESEARCH AGENT',
  heroSub: 'From questions to findings to papers. Claude Code + Codex CLI.',
  heroDescription: 'Understand the question, investigate the literature, build methods, choose experiments, and learn what to do next. Research Orchestrator coordinates 115 skills through two nested loops: the inner loop implements and tests methods; the outer loop interprets findings and revises hypotheses and routes. Carry ideas into discoveries, then shape the paper with one shared narrative.',
  actionChoose: 'Choose', actionAct: 'Act', actionLearn: 'Learn', actionWrite: 'Write',
  getStarted: 'Start researching', seeLoop: 'Watch the workflow',
  engineNote: 'Two engines. One skill catalog.',
  demoLabel: 'ILLUSTRATIVE',
  terminalPrompt: 'Investigate this question, choose a route, and move it forward',
  commitInit: 'Understand the question · read evidence · form hypotheses',
  commitProtocol: 'Choose experiments · state predictions · establish a baseline',
  commitResults: 'Build the method · measure outcomes · record findings',
  commitReflect: 'Interpret results · revise the method · choose a direction',
  terminalMemory: 'findings.md · research that remembers',
  visualCaption: 'Experiments move results. Reflection moves direction.',
  replay: 'Replay ↺',
  metricSkills: 'A shared research skill library',
  metricLoops: 'Experiment + reflection',
  metricEngineUnit: ' / engines', metricDirectionUnit: ' / directions',
  metricsSource: 'Counted from repository SKILL.md files · 2026-10-09',
  checkSources: 'View evidence ↗',
  workflowTitle: 'Decide what comes next. Then make it happen.',
  workflowDescription: 'Research Orchestrator chooses a route from your goal, existing assets, and project state, connecting literature, methods, experiments, and writing. The inner loop tests ideas; the outer loop makes sense of the results and turns findings into the next action.',
  readSpec: 'Read the workflow ↗',
  bootstrapTitle: 'Frame the question. Start working.',
  gate0: 'Clarify the goal → evidence-backed directions',
  gate1: 'Define the scope → an actionable plan',
  gatesNote: 'Build on the question and assets you already have. Start a probe when ready.',
  outerLoop: 'OUTER LOOP / SYNTHESIS & DIRECTION',
  synthesize: 'Synthesize', askWhy: 'Ask WHY', newHypothesis: 'New hypotheses',
  innerLoop: 'INNER LOOP / EXPERIMENT & VALIDATION',
  protocol: 'Protocol', experiment: 'Experiment', measure: 'Measure', learn: 'Learn',
  projectMemory: 'Memory across sessions',
  finalizeTitle: 'Make discovery durable.',
  output1: 'Evidence & synthesis', output2: 'Figures & progress reports',
  output3: 'Paper drafts & archives',
  finalizeNote: 'Deliver code, results, and findings. Develop a paper when the argument is ready.',
  routesHeading: 'Choose a route, not a rigid pipeline.',
  routeIdeaTitle: 'Start with a question or an idea',
  routeIdeaBody: 'Literature & ideation → Build a method → Test hypotheses',
  routeSotaTitle: 'Build on a strong existing method',
  routeSotaBody: 'Select an implementation → Bound reproduction → Iterate in place',
  routeForgeTitle: 'Forge a package for standalone runs',
  routeForgeBody: 'Fix evaluation & budget → Build the package → Run autonomously',
  routeContinuation: 'Use Autoresearch directly in an existing codebase; resume a loop with its contract and ledger intact. Choose Forge when standalone delivery is needed.',
  directionHeading: 'After the results, where next?',
  capabilitiesTitle: 'From understanding a question to making a discovery.',
  capabilitiesDescription: 'Literature reveals questions worth answering. Experiments turn ideas into methods. Writing connects findings into an argument. Shared research state and narrative plans keep the stages connected.',
  coordinationOwner: 'Coordinated work · Shared research state',
  stagePrepare: 'Research & ideation', stageOptimize: 'Methods & experiments',
  stageWrite: 'Writing & review',
  coordinationFoundation: 'Research workflows and domain methods, called on demand',
  researchTitle: 'Explore broadly. Read deeply. Think from evidence.',
  researchDescription: 'Map the field, then investigate the papers that matter. Turn consensus, disagreements, and open questions into candidate ideas, and use structured ideation and evaluation to find a question worth testing.',
  breadthLabel: 'BREADTH',
  breadthDescription: 'Map approaches, compare research directions, and identify unresolved gaps.',
  depthLabel: 'DEPTH',
  depthDescription: 'Use ArXiv MCP to retrieve and search full text. Keep versions and sources for the claims that matter.',
  ideaLabel: 'IDEATION',
  ideaDescription: 'Transfer ideas across fields, invert assumptions, and reframe problems. Turn feasible advances and original ideas into testable methods.',
  ideasSource: 'Explore the ideation methods ↗',
  evidenceToIdea: 'FROM PAPER EVIDENCE TO A TESTABLE IDEA',
  ideaHandoff: 'Evidence → candidate ideas → evaluation',
  researchOutput: 'Deliver: a sourced research brief, candidate directions, and an actionable research question.',
  forgeTitle: 'Make every experiment answer a research question.',
  forgeDescription: 'Experiments improve models, test hypotheses, and investigate failures. Research Orchestrator chooses a route for the question: build on an existing implementation, or use Experiment Forge to deliver a Karpathy-style autonomous task package. Autoresearch runs the unattended modify, measure, keep-or-revert inner loop.',
  optimizationLabel: 'CHOOSE EXPERIMENTS FOR THE QUESTION',
  metricAccuracy: 'Test hypotheses', metricLoss: 'Understand mechanisms',
  metricEfficiency: 'Improve models',
  experimentRange: 'Optimize accuracy, loss, or efficiency; use controls and diagnostics to distinguish explanations. Turn a diagnosed issue into a concrete method change, test it again, and retain the progress.',
  locked: 'LOCKED DATA + EVAL', editable: 'EDITABLE MODEL + TRAINING',
  contract: 'GOAL, BUDGET & SCOPE', dependencies: 'LOCKED DEPENDENCIES', ledger: 'RUN LEDGER',
  packageLabel: 'Optional standalone task package',
  executionLabel: 'Run the autonomous loop',
  loopBaseline: 'Baseline first', loopModify: 'Propose & modify',
  loopEvaluate: 'Train & evaluate', loopDecision: 'Keep improvements · Revert regressions',
  guardBudget: 'Time budget', guardRegression: 'Regression guard',
  guardNoise: 'Noise rechecks', guardLedger: 'Git record',
  optimizationNote: 'Each trial leaves code, measurements, and decisions. The outer loop synthesizes them into findings and chooses whether to deepen, broaden, revise, or conclude.',
  forgeSource: 'Explore the autonomous task specification ↗',
  searchPapers: 'Discover relevant work', downloadPaper: 'Retrieve text & version',
  searchText: 'Find & check the claim', traceable: 'TRACEABLE',
  writingTitle: 'A clear research story. A compelling paper.',
  writingDescription: 'Paper Narrative starts with your contribution and shapes one scientific story across the question, insight, method, and evidence. The abstract captures the discovery; the introduction builds the problem; sections and figures advance the argument; the conclusion answers the opening question and leaves a new understanding.',
  writingSharedPlan: 'Research findings feed one shared narrative plan across the abstract, introduction, figures, and conclusion. As discoveries evolve, the story and manuscript stay aligned. Scientific figures, citation checks, and dual review carry the paper through to delivery.',
  narrativeSource: 'Explore Paper Narrative ↗',
  writingSource: 'Explore the paper-production pipeline ↗',
  paperIdea: 'Core finding & argument structure',
  paperNarrative: 'Narrative, introduction & figure order',
  paperDraft: 'Abstract, body & conclusion',
  paperReview: 'Evidence checks + writing review',
  paperGate: 'Contribution-led · Evidence-connected · One coherent story',
  narrativeLensesTitle: 'Find the story in your contribution.',
  narrativeLensesDescription: 'Six narrative routes, selected and combined for the research.',
  narrativeRootTitle: 'Root-cause scalpel',
  narrativeRootBody: 'Move from a failure pattern to a mechanism and a targeted design.',
  narrativeReframeTitle: 'Counter-intuitive reframing',
  narrativeReframeBody: 'Revisit a default assumption and establish a more useful perspective.',
  narrativeTheoryTitle: 'Theory illuminates practice',
  narrativeTheoryBody: 'Turn formal results into a new understanding the reader can follow.',
  narrativeBenchmarkTitle: 'Benchmarks expose failure',
  narrativeBenchmarkBody: 'Make overlooked problems measurable and interpretable.',
  narrativeValueTitle: 'Societal value',
  narrativeValueBody: 'Connect technical choices and application value to a real need.',
  narrativeUnityTitle: 'A unifying principle',
  narrativeUnityBody: 'Connect multiple problems and results through one common principle.',
  narrativeLanding: 'Leave the reader with what this research establishes—and why it matters.',
  principleTitle: 'Commit the protocol before running the experiment.',
  principleDescription: 'Keep protocols and results in separate commits: a durable record that the plan preceded the run. Failed experiments and negative results belong here, too.',
  continuityTitle: 'Research that keeps its thread—and moves forward.',
  continuityDescription: 'Project memory, launch conditions, and cumulative budgets connect every turn. Turn preparation into a probe, diagnosis into a change, and results into the next action.',
  continuityMemoryTitle: 'Continue from the progress you have',
  continuityMemoryBody: 'Save the question, findings, decisions, and next action in project files. Read the state and findings before continuing, keeping the existing contract, ledger, and best result.',
  continuityProbeTitle: 'Ready to run? Start small.',
  continuityProbeBody: 'Launch the smallest real probe when the implementation runs, measurement is valid, and budget permits. Track preparation costs and specific blockers to move toward an observable result.',
  continuityReviseTitle: 'Turn diagnosis into a change',
  continuityReviseBody: 'Fix measurement or implementation issues where they occur. Revise or replace an ineffective candidate and test again. Informative negative results help choose the next step.',
  continuityBudgetTitle: 'Preserve the budget and the work',
  continuityBudgetBody: 'Carry resource records through continuation, pivots, and handoffs. At an agreed boundary, explicitly continue, narrow, or conclude with code, results, and findings preserved.',
  continuityHandoff: 'Research records connect experiments and writing: establish the findings, then shape a mature contribution into a paper.',
  continuityStart: 'Start with a clear question ↗',
  skillsTitle: '115 skills. A method for every stage.',
  skillsDescription: 'From AlphaFold2 to DeepSpeed, 115 research skills span literature, experiments, writing, and specialist methods. Orchestrator calls on the right expertise as the project needs it.',
  allSkills: 'All skills', searchPlaceholder: 'Find a skill, e.g. deepspeed',
  skillCategoriesNote: '12 curated topic groups · Open any skill to read its source',
  skillsFootnote: 'One library of 115 research skills, adapted for Claude Code and Codex CLI. Counted from skills/*/SKILL.md files.',
  enginesTitle: 'Your engine. A shared research mindset.',
  enginesDescription: 'Shared research conventions and skill design, adapted for two CLIs. Use familiar tools to carry a research project from question to evidence.',
  claudeDescription: '115 skills and 4 specialist subagents. Native agent collaboration and in-session heartbeats advance the research; saved project state carries the work into the next session.',
  codexDescription: 'The same 115 skills. Background experiments, completion markers, and memory connect long tasks; a reference driver saves a session ID per project for cross-turn continuation.',
  startTitle1: 'Your next discovery.', startTitle2: 'Starts in your terminal.',
  startDescription: 'Install and sign in to your chosen CLI, then add research skills in a Bash environment. Existing configuration is backed up. Start a fresh session to begin.',
  startMeta: 'Source available · Local workflows · Your compute',
  installLabel: 'Install the research skills', copy: 'Copy',
  installNote: 'These three lines install skills and research conventions. Full-text retrieval needs a separate ArXiv MCP setup.',
  mcpSetup: 'Set up ArXiv MCP full-text retrieval',
  mcpNote: 'Requires Python and pip. Commands below use the default user installation path. Start Codex once first to create its configuration.',
  mcpCheck: 'Restart the CLI and check that arxiv tools loaded. Adjust the command if you use a custom installation path.',
  firstPromptLabel: 'THEN, GIVE IT YOUR FIRST QUESTION',
  firstPrompt: 'Use research-orchestrator: my question is … , my code and data are in … , and my budget is … . Choose a route and start the smallest real experiment when ready. Learn from the results, revise the method, preserve progress, and shape a paper when the contribution is ready.',
  continuationSetup: 'Advanced: keep the project moving',
  continuationNote: 'Claude Code uses in-session heartbeats. The Codex reference driver resumes a session per project, advances one turn per invocation, and can connect to your scheduler. Establish the project state and environment first.',
  continuationSource: 'Read the continuation conventions ↗',
  evidenceTitle: 'Sources and demonstration notes',
  evidenceNote: 'Skill counts checked on 2026-10-09: Claude 70c8d67 and Codex 928f748, each with the same 115 skill names. The terminal and handwritten-digit animations illustrate the workflow. The 12 topic groups are editorial categories for this site.',
  autonomyNote: 'Autonomous work uses your configured CLI, compute, and budget. The skill catalogue is shared; execution and continuation are adapted to each engine. Long-running drivers are configured as needed; existing launchers are not replaced automatically.',
  footerLine: 'Autonomy for research. Evidence for discovery.',
  footerThanks: 'Thanks to the open-source projects: ',
  skip: 'Skip to content', navWorkflow: 'Workflow', navCapabilities: 'Capabilities',
  navSkills: 'Skills', navStart: 'Get started'
};
const chinese={};document.querySelectorAll('[data-i18n]').forEach(el=>chinese[el.dataset.i18n]=el.textContent);chinese.searchPlaceholder='搜索技能，例如 deepspeed';
const $=id=>document.getElementById(id);let language='zh',direction='deepen',engine='all',install='claude',expanded=false;
try{if(localStorage.getItem('research-language')==='en')language='en'}catch{}
const urlLanguage=new URLSearchParams(location.search).get('lang');if(['en','zh'].includes(urlLanguage))language=urlLanguage;
const t=key=>(language==='en'?english:chinese)[key]??chinese[key]??key;
const directions={deepen:['深挖机制：把已经出现的信号，变成更具体、可验证的子假设。','Go deeper: turn an observed signal into a more specific, testable hypothesis.'],broaden:['拓宽问题：从已有结果出发，检验新的设置、任务或适用边界。','Broaden the question: test new settings, tasks, or boundaries suggested by the results.'],pivot:['重新定向：当有效证据反驳了核心主张，带着已学到的事实调整路线。','Change direction when valid evidence refutes a core claim, carrying the findings into a revised route.'],conclude:['综合与交付：整理代码、结果和已知发现；贡献形成完整论证时进入论文写作。','Synthesize and deliver code, results, and findings; develop a paper when the contribution supports a coherent argument.']};
function setDirection(){document.querySelectorAll('[data-direction]').forEach(b=>{const active=b.dataset.direction===direction;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('direction-panel').textContent=directions[direction][language==='en'?1:0];$('direction-panel').setAttribute('aria-labelledby','direction-'+direction)}
function commands(){return `git clone https://github.com/Yichen-ZJU/${install}-for-research.git\ncd ${install}-for-research\nbash ${install==='claude'?'install.sh':'setup.sh install'}`}
function setContinuation(){
 const claude=install==='claude';
 $('continuation-instruction').textContent=language==='zh'
  ? (claude?'让 Orchestrator 在当前会话安排研究心跳；新会话指向原项目，先读状态与 findings 再继续。':'参考驱动：skills/research-orchestrator/templates/autoloop-reference.sh。传入已有项目目录，每次推进一轮；接入调度器后按项目会话 ID 续接。')
  : (claude?'Ask Orchestrator to arrange research heartbeats in the active session. In a new session, point to the original project and read its state and findings first.':'Reference driver: skills/research-orchestrator/templates/autoloop-reference.sh. Pass an existing project directory; each invocation advances one turn. A scheduler can resume the project session across turns.');
 $('continuation-source').href=claude
  ? `https://github.com/Yichen-ZJU/claude-for-research/blob/${window.RESEARCH_DATA.commits.claude}/skills/research-orchestrator/SKILL.md`
  : `https://github.com/Yichen-ZJU/codex-for-research/blob/${window.RESEARCH_DATA.commits.codex}/skills/research-orchestrator/templates/autoloop-reference.sh`;
}
function setInstall(){document.querySelectorAll('[data-install]').forEach(b=>{const active=b.dataset.install===install;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('install-panel').setAttribute('aria-labelledby','install-'+install);$('install-code').textContent=commands();$('mcp-code').textContent=install==='claude'?'python3 -m pip install --user arxiv-mcp-server\nclaude mcp add --scope user arxiv -- "$HOME/.local/bin/arxiv-mcp-server"':'python3 -m pip install --user arxiv-mcp-server\nbash scripts/register-arxiv-mcp.sh';setContinuation()}
function renderSkills(){
 const query=$('skill-search').value.trim().toLowerCase();const groups=window.RESEARCH_DATA.groups.map(g=>({...g,skills:g.skills.filter(s=>(engine==='all'||s[engine])&&(s.name.includes(query)||g.zh.includes(query)||g.en.toLowerCase().includes(query)))})).filter(g=>g.skills.length);const visible=(expanded||query)?groups:groups.slice(0,6);const total=groups.reduce((n,g)=>n+g.skills.length,0),shown=visible.reduce((n,g)=>n+g.skills.length,0);
 $('skills-count').textContent=language==='zh'?`${total} 个匹配技能 · 当前显示 ${shown} 个`:`${total} matching skills · ${shown} shown`;const fragment=document.createDocumentFragment();
 for(const g of visible){const article=document.createElement('article');article.className='skill-category';const header=document.createElement('div');header.className='category-header';const icon=document.createElement('i');icon.className='category-icon';icon.textContent=g.icon;icon.setAttribute('aria-hidden','true');const h=document.createElement('h3');h.textContent=g[language];const count=document.createElement('span');count.textContent=String(g.skills.length).padStart(2,'0');header.append(icon,h,count);const tags=document.createElement('div');tags.className='skill-tags';for(const s of g.skills){const a=document.createElement('a'),e=engine==='claude'?'claude':'codex';a.className='skill-tag';a.href=`https://github.com/Yichen-ZJU/${e}-for-research/blob/${window.RESEARCH_DATA.commits[e]}/skills/${s.name}/SKILL.md`;a.textContent=s.name;a.target='_blank';a.rel='noopener noreferrer';a.title=(s.claude?'Claude Code + Codex CLI':'Codex CLI')+' · SKILL.md';tags.append(a)}article.append(header,tags);fragment.append(article)}
 if(!total){const p=document.createElement('p');p.className='empty-skills';p.textContent=language==='zh'?'没有匹配的技能，试试其他关键词。':'No matching skills. Try another keyword.';fragment.append(p)}$('skill-grid').replaceChildren(fragment);$('show-skills').hidden=groups.length<=6||Boolean(query);$('show-skills').setAttribute('aria-expanded',String(expanded));$('show-skills').textContent=expanded?(language==='zh'?'收起技能库 ↑':'Show fewer skills ↑'):(language==='zh'?`展开全部 ${groups.length} 组技能 ↓`:`Explore all ${groups.length} topic groups ↓`)
}
function setLanguage(){document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=language==='zh'?'Lemvo · 会思考，会行动的科研 Agent':'Lemvo — A research agent that thinks and acts';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('language').textContent=language==='zh'?'EN ↗':'中文 ↗';$('language').setAttribute('aria-label',language==='zh'?'Switch to English':'切换到中文');$('skill-search').setAttribute('aria-label',language==='zh'?'搜索技能':'Search skills');document.querySelector('meta[name="description"]').content=t('heroDescription');document.querySelector('meta[property="og:title"]').content=document.title;document.querySelector('meta[property="og:description"]').content=t('heroDescription');document.querySelector('meta[name="twitter:title"]').content=document.title;document.querySelector('meta[name="twitter:description"]').content=t('heroDescription');setDirection();setInstall();renderSkills();document.dispatchEvent(new CustomEvent('research-language-change',{detail:{language}}))}
$('language').addEventListener('click',()=>{language=language==='zh'?'en':'zh';try{localStorage.setItem('research-language',language)}catch{}setLanguage()});
document.querySelectorAll('[data-direction]').forEach(b=>b.addEventListener('click',()=>{direction=b.dataset.direction;setDirection()}));document.querySelectorAll('[data-install]').forEach(b=>b.addEventListener('click',()=>{install=b.dataset.install;setInstall()}));document.querySelectorAll('[data-engine]').forEach(b=>b.addEventListener('click',()=>{engine=b.dataset.engine;document.querySelectorAll('[data-engine]').forEach(a=>a.setAttribute('aria-pressed',String(a===b)));renderSkills()}));
for(const selector of ['[data-direction]','[data-install]']){const buttons=[...document.querySelectorAll(selector)];buttons.forEach((b,i)=>b.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(i+1)%buttons.length;if(event.key==='ArrowLeft')next=(i+buttons.length-1)%buttons.length;if(event.key==='Home')next=0;if(event.key==='End')next=buttons.length-1;if(next!==undefined){event.preventDefault();buttons[next].click();buttons[next].focus()}}))}
$('skill-search').addEventListener('input',renderSkills);$('show-skills').addEventListener('click',()=>{expanded=!expanded;renderSkills();if(!expanded)$('skills').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})});document.addEventListener('keydown',event=>{if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)&&!document.activeElement.isContentEditable){event.preventDefault();$('skill-search').focus()}});
let toastTimer;function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600)}
$('copy-install').addEventListener('click',async()=>{let copied=false;try{await navigator.clipboard.writeText(commands());copied=true}catch{const field=document.createElement('textarea');field.value=commands();field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();try{copied=document.execCommand('copy')}catch{}field.remove();$('copy-install').focus()}toast(copied?(language==='zh'?'安装命令已复制':'Install commands copied'):(language==='zh'?'请选中命令后手动复制':'Please select and copy the commands manually'))});
let timers=[];function replay(){timers.forEach(clearTimeout);timers=[];const lines=[...document.querySelectorAll('[data-stage]')];if(matchMedia('(prefers-reduced-motion: reduce)').matches){lines.forEach(line=>line.classList.add('active'));return}lines.forEach(line=>line.classList.remove('active'));lines.forEach((line,i)=>timers.push(setTimeout(()=>line.classList.add('active'),300+i*750)))}$('replay').addEventListener('click',replay);setLanguage();replay();
